### ISSUE TITLE
Add proper documentation to the project

### ISSUE THREAD

**Issue by GuilhermeBn198** [yasse-ofc/yasse-crawlers#13]
# Use of standardized documentation to facilitates the comprehension of the project's complexities and goals:
- [x] Software Project Management Plan (SPMP)
- [x] Software Requirements Specifications (SRS)
- [ ] Software Design Description (SDD)
- [ ] Software Test Documentation (STD

**Comment by GuilhermeBn198** [comment]
the first document has been issued in the pr #12  
- Software Project Management Plan (SPMP)

**Comment by ed-henrique** [comment]
We are currently searching for a better way to document the app. Some articles that may help are as follow:

- [Beginner's Guide to Docs](https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/)
- [How to Write Good Documentation](https://guides.lib.berkeley.edu/how-to-write-good-documentation)
- [Writing Great Docs for Your App](https://blog.developer.atlassian.com/writing-great-docs-for-your-app/)

**Comment by GuilhermeBn198** [comment]
The first version of the second document is available! check it out at #20 
 - Software Requirements Specifications (SRS)

**Comment by ed-henrique** [comment]
This issue will now be addressed for Yasse as a whole, not just for this rep, so I'm closing the issue here and moving it to the organization projects.
